import { useEffect, useRef, useState } from 'react'
import { Markdown } from '../lib/markdown'
import { listArtifacts, readArtifact } from '../lib/runsApi'
import type { Artifact, RunEvent, RunState } from '../lib/runsApi'
import { Button, Status } from '../lib/ui'
type Props = { run: RunState | null; events: RunEvent[]; live: boolean; refreshKey: number }
export default function ArtifactRail({ run, events, live, refreshKey }: Props) { const [tab, setTab] = useState<'artifact'|'state'|'events'>('artifact'); const [artifacts, setArtifacts] = useState<Artifact[]>([]); const [selected, setSelected] = useState<{name:string;text:string}|null>(null); const [raw, setRaw] = useState(false); const end = useRef<HTMLDivElement>(null)
  useEffect(() => { if (!run) return; void listArtifacts(run.run_id).then(x => setArtifacts(x.artifacts)).catch(() => undefined) }, [run, refreshKey])
  useEffect(() => { if (live) end.current?.scrollIntoView({ block: 'nearest' }) }, [events, live])
  const choose = (name: string) => void readArtifact(run!.run_id, name).then(setSelected).catch(() => setSelected(null))
  return <aside className="flex min-h-0 min-w-0 flex-col bg-[var(--hub-bg-surface)] md:w-[42%]"><div className="flex gap-0 border-b border-border-subtle px-3 pt-2">{([['artifact','Artifact'],['state','Trạng thái'],['events','Sự kiện']] as const).map(([id,label]) => <Button key={id} variant={tab === id ? 'secondary' : 'ghost'} size="sm" onClick={() => setTab(id)}>{label}</Button>)}</div><div className="min-h-0 flex-1 overflow-y-auto p-4 md:p-5">{tab === 'artifact' && <>{artifacts.length === 0 ? <div className="text-xs text-muted">Chưa có artifact</div> : <div className="mb-4 space-y-2">{artifacts.map(a => <Button key={a.name} variant="ghost" size="sm" onClick={() => choose(a.name)} className={`block w-full text-left font-mono ${selected?.name === a.name ? 'text-primary' : 'text-secondary'}`}>▤ <b>{a.name}</b> · {a.chars} ký tự</Button>)}</div>}{selected && <div className="text-[13px]"><div className="mb-3 font-mono text-[11px] text-muted">{selected.name}</div><Markdown source={selected.text} /></div>}</>}{tab === 'state' && <StateView run={run} raw={raw} setRaw={setRaw} />}{tab === 'events' && <div className="space-y-2 font-mono text-[10px] text-secondary">{events.length === 0 && <div className="text-muted">Chưa có sự kiện</div>}{events.map((event,index) => <div key={`${event.ts}-${index}`} className="border-b border-border-subtle pb-1">{event.ts ?? '—'} · {event.type ?? event.event ?? 'event'}{event.node ? ` · ${event.node}` : ''}<div className="truncate text-muted">{shortEvent(event)}</div></div>)}<div ref={end} /></div>}</div></aside> }
function StateView({ run, raw, setRaw }: { run: RunState | null; raw: boolean; setRaw: (x:boolean)=>void }) { const meta = run?.metadata ?? {}; const completed = meta.completed_nodes; return <div className="space-y-3 text-xs text-secondary"><div><b className="text-primary">Trạng thái</b><div className="font-mono">{run?.status ?? 'chưa chạy'}</div></div><div><b className="text-primary">Node hiện tại</b><div className="font-mono">{String(meta.current_node ?? '—')} · index {String(meta.node_index ?? '—')}</div></div><div><b className="text-primary">Đã hoàn tất</b><div className="font-mono">{Array.isArray(completed) ? completed.join(', ') || '—' : String(completed ?? '—')}</div></div><div><b className="text-primary">Mục tiêu</b><div>{String(meta.objective ?? '—')}</div></div><Button variant="ghost" size="sm" onClick={() => setRaw(!raw)}> <Status kind={raw ? 'ready' : 'paused'} label={raw ? 'Ẩn raw state' : 'Hiện raw state'} /></Button>{raw && <pre className="overflow-x-auto whitespace-pre-wrap rounded-[var(--hub-radius-sm)] border border-border-subtle bg-surface p-2 font-mono text-[10px] text-secondary">{JSON.stringify(run, null, 2)}</pre>}</div> }
function shortEvent(event: RunEvent) { const value = event.text ?? event.message ?? event.reason; return value ? String(value).replace(/\s+/g, ' ').slice(0, 120) : '—' }


