// UI copy for the misc area. Owned by one migration batch to keep parallel work conflict-free.
export const misc = {
  'misc.loadDataFailed': 'Unable to load data', 'misc.overview.subtitle': 'Overview from available endpoints.', 'misc.overview.providersAvailable': '{online} of {total} available', 'misc.overview.loading': 'Loading', 'misc.overview.notApplicable': 'This metric is not applicable to the current response.', 'misc.overview.recentRuns': 'Recent runs', 'misc.overview.viewAll': 'View all', 'misc.overview.run': 'Run', 'misc.overview.agent': 'Agent', 'misc.overview.status': 'Status', 'misc.overview.started': 'Started', 'misc.overview.elapsed': 'Elapsed', 'misc.overview.copyRunId': 'Copy run ID', 'misc.overview.copyThreadId': 'Copy thread ID', 'misc.overview.approvalRequired': 'approval required',
  'misc.files.subtitle': 'Files belonging to each run.', 'misc.files.loadRunsFailed': 'Unable to load runs', 'misc.files.loadFilesFailed': 'Unable to load files', 'misc.files.uploadFailed': 'Unable to upload file', 'misc.files.chooseRun': 'Choose a run', 'misc.files.name': 'Name', 'misc.files.size': 'Size', 'misc.files.updated': 'Updated', 'misc.files.download': 'Download', 'misc.files.emptyTitle': 'No files yet', 'misc.files.emptyForRun': 'Upload a file for this run.', 'misc.files.emptyNoRun': 'Choose a run.',
  'misc.hooks.subtitle': 'Automate runtime events.', 'misc.hooks.loadFailed': 'Unable to load hooks', 'misc.hooks.createFailed': 'Unable to create hook', 'misc.hooks.namePlaceholder': 'Hook name', 'misc.hooks.eventLabel': 'Event', 'misc.hooks.new': 'New hook', 'misc.hooks.name': 'Name', 'misc.hooks.event': 'Event', 'misc.hooks.agent': 'Agent', 'misc.hooks.triggerPoint': 'Trigger point', 'misc.hooks.executed': 'Executed', 'misc.hooks.status': 'Status', 'misc.hooks.lastUpdated': 'Last updated', 'misc.hooks.emptyTitle': 'No hooks yet', 'misc.hooks.emptyDescription': 'Create a webhook hook from a real runtime event.',
  'misc.sessions.loadFailed': 'Unable to load sessions', 'misc.sessions.loadReplayFailed': 'Unable to load replay', 'misc.sessions.eyebrow': 'CHAT', 'misc.sessions.title': 'Saved sessions', 'misc.sessions.retry': 'Retry', 'misc.sessions.empty': 'No sessions yet', 'misc.sessions.time': 'Time', 'misc.sessions.project': 'Project', 'misc.sessions.replay': 'Replay', 'misc.sessions.loadingReplay': 'Loading replay…', 'misc.sessions.toolCalls': '{count} tool',
  'misc.placeholder.buildPhase': 'Will be built in phase {phase}', 'misc.gate.waiting': 'GATE · awaiting your decision', 'misc.gate.defaultPrompt': 'Workflow is awaiting your decision.', 'misc.gate.sending': 'Sending…', 'misc.gate.approve': 'Approve', 'misc.gate.reject': 'Reject',
  'misc.runs.workspace': 'Runs workspace', 'misc.runs.startPrompt': 'Choose a workflow and objective to start a run.', 'misc.runs.empty': 'Spine appears after the workflow is validated.', 'misc.runs.waitingNode': 'Waiting for this node…', 'misc.runs.hideThinking': 'Hide reasoning', 'misc.runs.showThinking': 'Show reasoning',
  'misc.chart.ariaLabel': 'Daily trend chart', 'misc.chart.empty': 'No data yet.', 'misc.ui.remove': 'Remove', 'misc.status.ready': 'Ready', 'misc.status.running': 'Running', 'misc.status.paused': 'Paused', 'misc.status.setupRequired': 'Setup required', 'misc.status.notInstalled': 'Not installed', 'misc.status.rateLimited': 'Rate limited', 'misc.status.error': 'Error', 'misc.status.offline': 'Offline',
} as const
