import { useEffect, useRef, useState } from 'react'
import { ApiError, api } from '../lib/api'
import { t } from '../lib/i18n'
import { Button, EmptyState, Select } from '../lib/ui'
type Run = { run_id: string; status: string }; type Item = { name: string; size: number; updated_at: string | number }
export default function FilesPage() { const [runs, setRuns] = useState<Run[]>([]), [run, setRun] = useState(''), [files, setFiles] = useState<Item[]>([]), [error, setError] = useState(''), input = useRef<HTMLInputElement>(null)
  const load = () => void api<Run[]>('/api/agent/runs').then(rows => { setRuns(rows); setRun(current => current || rows[0]?.run_id || '') }).catch(e => setError(e instanceof ApiError ? e.message : t('misc.files.loadRunsFailed')))
  const loadFiles = () => run && void api<Item[]>(`/api/runs/${encodeURIComponent(run)}/files`).then(setFiles).catch(e => setError(e instanceof ApiError ? e.message : t('misc.files.loadFilesFailed')))
  useEffect(load, []); useEffect(() => { if (run) void api<Item[]>(`/api/runs/${encodeURIComponent(run)}/files`).then(setFiles).catch(e => setError(e instanceof ApiError ? e.message : t('misc.files.loadFilesFailed'))) }, [run])
  const upload = async (file: File) => { const form = new FormData(); form.append('file', file); try { await api(`/api/runs/${encodeURIComponent(run)}/files`, { method: 'POST', body: form }); loadFiles() } catch (e) { setError(e instanceof ApiError ? e.message : t('misc.files.uploadFailed')) } }
  return <div className="flex h-full min-h-0 flex-col gap-space-4 p-space-6"><div className="flex items-end justify-between"><div><h1 className="text-title font-semibold text-primary">Files</h1><p className="mt-space-1 text-caption text-secondary">{t('misc.files.subtitle')}</p></div><Button variant="primary" disabled={!run} onClick={() => input.current?.click()}>Upload</Button><input ref={input} className="hidden" type="file" onChange={e => e.target.files?.[0] && void upload(e.target.files[0])} /></div>{error && <p className="text-caption text-error">{error}</p>}<Select value={run} onChange={e => setRun(e.target.value)} className="max-w-[420px]"><option value="">{t('misc.files.chooseRun')}</option>{runs.map(item => <option key={item.run_id} value={item.run_id}>{item.run_id} · {item.status}</option>)}</Select><section className="min-h-0 flex-1 overflow-auto rounded-lg border border-border-subtle bg-surface">{files.length ? <table className="w-full text-left"><thead><tr className="border-b border-border-subtle text-caption text-muted">{[t('misc.files.name'), t('misc.files.size'), t('misc.files.updated'), ''].map(x => <th key={x} className="p-space-3">{x}</th>)}</tr></thead><tbody>{files.map(item => <tr key={item.name} className="border-b border-border-subtle"><td className="p-space-3">{item.name}</td><td className="p-space-3">{item.size} B</td><td className="p-space-3">{String(item.updated_at)}</td><td className="p-space-3"><a className="text-accent" href={`/api/runs/${encodeURIComponent(run)}/files/${encodeURIComponent(item.name)}`}>{t('misc.files.download')}</a> <Button size="sm" variant="ghost" onClick={() => void api(`/api/runs/${encodeURIComponent(run)}/files/${encodeURIComponent(item.name)}`, { method: 'DELETE' }).then(loadFiles)}>{t('common.delete')}</Button></td></tr>)}</tbody></table> : <div className="p-space-6"><EmptyState title={t('misc.files.emptyTitle')} description={run ? t('misc.files.emptyForRun') : t('misc.files.emptyNoRun')} /></div>}</section></div> }
