import { useEffect, useState } from 'react'
import { ApiError, api } from '../lib/api'
import { t } from '../lib/i18n'
import { Button, EmptyState, Input, Select } from '../lib/ui'
type Hook = { id: string; name: string; event: string; trigger_point: string; agent_id: string; enabled: boolean; executed_count: number; last_run_at: string | null; last_status: string | null; action: { type: string; url?: string; path?: string } }
export default function HooksPage() { const [rows, setRows] = useState<Hook[]>([]), [events, setEvents] = useState<string[]>([]), [agents, setAgents] = useState<{ id: string }[]>([]), [error, setError] = useState(''), [name, setName] = useState(''), [event, setEvent] = useState(''), [agentId, setAgentId] = useState(''), [target, setTarget] = useState('')
  // A hook only fires for events carrying its agent_id, so the picker is required, not a convenience.
  const load = () => void Promise.all([api<Hook[]>('/api/hooks'), api<string[]>('/api/hooks/events'), api<{ id: string }[]>('/api/agents')]).then(([h,e,a]) => { setRows(h); setEvents(e); setAgents(a); setEvent(x => x || e[0] || ''); setAgentId(x => x || a[0]?.id || '') }).catch(e => setError(e instanceof ApiError ? e.message : t('misc.hooks.loadFailed')))
  useEffect(load, []); const create = async () => { try { await api('/api/hooks', { method: 'POST', body: JSON.stringify({ name, event, agent_id: agentId, trigger_point: 'runtime', enabled: true, action: { type: 'webhook', url: target } }) }); setName(''); setTarget(''); load() } catch (e) { setError(e instanceof ApiError ? e.message : t('misc.hooks.createFailed')) } }
  const headers = [t('misc.hooks.name'), t('misc.hooks.event'), t('misc.hooks.agent'), t('misc.hooks.triggerPoint'), t('misc.hooks.executed'), t('misc.hooks.status'), t('misc.hooks.lastUpdated')]
  return <div className="flex h-full min-h-0 flex-col gap-space-4 p-space-6"><div><h1 className="text-title font-semibold text-primary">Hooks</h1><p className="mt-space-1 text-caption text-secondary">{t('misc.hooks.subtitle')}</p></div>{error && <p className="text-caption text-error">{error}</p>}<div className="flex flex-wrap gap-space-2"><Input value={name} onChange={e => setName(e.target.value)} placeholder={t('misc.hooks.namePlaceholder')} /><Select value={event} onChange={e => setEvent(e.target.value)} aria-label={t('misc.hooks.eventLabel')}>{events.map(x => <option key={x}>{x}</option>)}</Select><Select value={agentId} onChange={e => setAgentId(e.target.value)} aria-label={t('misc.hooks.agent')}>{agents.map(x => <option key={x.id}>{x.id}</option>)}</Select><Input value={target} onChange={e => setTarget(e.target.value)} placeholder="Webhook URL" /><Button variant="primary" disabled={!name || !event || !agentId || !target} onClick={() => void create()}>{t('misc.hooks.new')}</Button></div><section className="min-h-0 flex-1 overflow-auto rounded-lg border border-border-subtle bg-surface">{rows.length ? <table className="w-full text-left"><thead><tr className="border-b border-border-subtle text-caption text-muted">{headers.map(x => <th key={x} className="p-space-3">{x}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b border-border-subtle"><td className="p-space-3">{row.name}</td><td className="p-space-3">{row.event}</td><td className="p-space-3 font-mono">{row.agent_id || '—'}</td><td className="p-space-3">{row.trigger_point}</td><td className="p-space-3">{row.executed_count}</td><td className="p-space-3">{row.last_status || '—'}</td><td className="p-space-3">{row.last_run_at || '—'}</td></tr>)}</tbody></table> : <div className="p-space-6"><EmptyState title={t('misc.hooks.emptyTitle')} description={t('misc.hooks.emptyDescription')} /></div>}</section></div> }
