import { useEffect, useState } from 'react'
import { api, ApiError } from '../lib/api'
import Table from '../lib/Table'
import { Button } from '../lib/ui'
type Session = { session: string; source: string; ts: string; project: string | null }
type Replay = { outline?: Record<string, unknown>[]; agent?: Record<string, unknown>[]; monitor?: Record<string, unknown>[] }
export default function SessionsPage() { const [rows, setRows] = useState<Session[]>([]); const [selected, setSelected] = useState<Session | null>(null); const [replay, setReplay] = useState<Replay | null>(null); const [error, setError] = useState(''); const load = () => { setError(''); void api<Session[]>('/api/sessions').then(setRows).catch(e => setError(e instanceof ApiError ? e.message : 'Không thể tải phiên')) }; useEffect(load, []); const choose = (row: Session) => { setSelected(row); setReplay(null); void api<Replay>(`/api/sessions/${encodeURIComponent(row.session)}/replay`).then(setReplay).catch(e => setError(e instanceof ApiError ? e.message : 'Không thể tải replay')) }; return <div className="flex h-full min-h-0 flex-col gap-4 p-7"><div><div className="mb-2 text-[length:var(--hub-section-size)] font-semibold uppercase tracking-[var(--hub-section-tracking)] text-muted">TRÒ CHUYỆN</div><h1 className="text-[length:var(--hub-title-size)] font-semibold">Phiên đã lưu</h1></div>{error && <div className="flex items-center gap-3 text-xs text-error">{error}<Button variant="secondary" size="sm" onClick={load}>Thử lại</Button></div>}{!error && rows.length === 0 ? <div className="text-xs text-secondary">Chưa có phiên nào</div> : <div className="min-h-0 overflow-auto"><Table headers={['Session / id', 'Agent / source', 'Thời gian', 'Project']} >{rows.map(row => <tr key={row.session} onClick={() => choose(row)} className={`cursor-pointer hover:bg-elevated ${selected?.session === row.session ? 'bg-elevated' : ''}`}><td className="px-3 py-3 font-mono text-primary">{row.session}</td><td className="px-3 py-3 text-secondary">{row.source}</td><td className="px-3 py-3 font-mono text-[11px] text-secondary">{row.ts}</td><td className="px-3 py-3 text-secondary">{row.project ?? '—'}</td></tr>)}</Table></div>}{selected && <section className="min-h-0 flex-1 overflow-auto rounded-lg border border-border-subtle bg-surface p-4"><h2 className="mb-3 text-sm font-semibold">Replay · <span className="font-mono text-xs text-secondary">{selected.session}</span></h2>{replay ? <ReplaySteps replay={replay} /> : <div className="text-xs text-secondary">Đang tải replay…</div>}</section>}</div> }

function ReplaySteps({ replay }: { replay: Replay }) { const steps: Record<string, unknown>[] = [...(replay.outline ?? []).map(x => ({ ...x, role: 'outline' })), ...(replay.agent ?? []), ...(replay.monitor ?? []).map(x => ({ ...x, role: String(x.kind ?? 'tool') }))]; return <div className="space-y-2 font-mono text-xs">{steps.map((step, index) => <details key={index} className="rounded-sm border border-border-subtle p-2"><summary className="cursor-pointer text-secondary">{String(step.role)} · {String(step.ts ?? '')} {Array.isArray(step.tool_calls) ? `· ${step.tool_calls.length} tool` : ''}</summary><pre className="mt-2 whitespace-pre-wrap text-primary">{String(step.text ?? step.summary ?? JSON.stringify(step, null, 2))}</pre></details>)}</div> }



