import { useEffect, useMemo, useState } from 'react'
import { ApiError, api } from '../lib/api'
import { Markdown } from '../lib/markdown'
import Table from '../lib/Table'
import { Button, Select } from '../lib/ui'

type Skill = { id: string; name: string; description: string; source: string; path: string; content_hash: string; coverage: string[]; last_used: string | null; use_count_30d: number | null }
type Detail = Skill & { content: string; files: string[] }; type Drift = { name: string; variants: { id: string; source: string; path: string; content_hash: string; mtime: string | null }[]; in_sync: boolean }; type Log = Record<string, unknown>
export default function SkillsPage() {
  const [skills, setSkills] = useState<Skill[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [drift, setDrift] = useState<Drift[]>([]); const [log, setLog] = useState<Log[]>([]); const [target, setTarget] = useState(''); const [error, setError] = useState(''); const targets = useMemo(() => [...new Set(skills.map(skill => skill.source))], [skills])
  const load = () => { setError(''); void Promise.all([api<Skill[]>('/api/skill-library'), api<Drift[]>('/api/skill-library/drift'), api<Log[]>('/api/skill-library/deploy-log')]).then(([s, d, l]) => { setSkills(s); setDrift(d); setLog(l); setTarget(current => current || s[0]?.source || '') }).catch(e => setError(e instanceof ApiError ? e.message : 'Không thể tải skill library')) }
  useEffect(load, [])
  const choose = (skill: Skill) => { setError(''); void api<Detail>(`/api/skill-library/${skill.id}`).then(setDetail).catch(e => setError(e instanceof ApiError ? e.message : 'Không thể tải skill')) }
  const deploy = async (skill: Skill) => { if (!target) return; try { await api(`/api/skill-library/${encodeURIComponent(skill.id)}/deploy`, { method: 'POST', body: JSON.stringify({ target }) }); setLog(await api<Log[]>('/api/skill-library/deploy-log')); setError('') } catch (e) { setError(e instanceof ApiError ? e.message : 'Triển khai thất bại') } }
  return <div className="flex h-full min-h-0 flex-col gap-4 p-7"><div><div className="mb-2 text-[length:var(--hub-section-size)] font-semibold uppercase tracking-[var(--hub-section-tracking)] text-muted">ĐIỀU PHỐI</div><h1 className="text-[length:var(--hub-title-size)] font-semibold">Skills</h1></div>{error && <div className="text-xs text-error">{error}</div>}<section className="min-h-0 overflow-auto"><Table headers={['Name', 'Source', 'Description', 'Telemetry', 'Deploy']}>{skills.map(skill => <tr key={skill.id} onClick={() => choose(skill)} className="cursor-pointer hover:bg-elevated"><td className="px-3 py-2 font-mono text-primary">{skill.name}</td><td className="px-3 py-2 text-secondary">{skill.source}</td><td className="max-w-sm px-3 py-2 text-secondary">{skill.description || '—'}</td><td className="px-3 py-2 font-mono text-[10px] text-muted">{skill.use_count_30d ?? '—'} / {skill.last_used ?? '—'}</td><td className="px-3 py-2"><Button variant="secondary" size="sm" onClick={e => { e.stopPropagation(); void deploy(skill) }}>Triển khai</Button></td></tr>)}</Table></section><div className="flex flex-wrap items-center gap-2 text-xs"><span>Đích triển khai</span><Select value={target} onChange={e => setTarget(e.target.value)} className="rounded-sm border border-border-subtle bg-elevated px-2 py-1">{targets.map(value => <option key={value}>{value}</option>)}</Select></div>{detail && <section className="min-h-0 overflow-auto rounded-lg border border-border-subtle bg-surface p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-mono text-sm">{detail.name}</h2><div className="text-[10px] text-muted">{detail.id} · {detail.source} · {detail.content_hash}</div></div><Button variant="ghost" size="sm" onClick={() => setDetail(null)}>×</Button></div><Markdown source={detail.content} /></section>}<section className="rounded-lg border border-border-subtle bg-surface p-4"><h2 className="mb-2 text-xs font-semibold">Drift</h2>{drift.filter(row => !row.in_sync).length ? drift.filter(row => !row.in_sync).map(row => <div key={row.name} className="mb-2 text-xs text-warning"><span className="font-mono">{row.name}</span> · {row.variants.length} variants</div>) : <div className="text-xs text-muted">Không có drift</div>}<details className="mt-3 text-xs"><summary className="cursor-pointer text-secondary">Deploy log ({log.length})</summary>{log.map((row, index) => <pre key={index} className="mt-1 whitespace-pre-wrap font-mono text-[10px] text-muted">{JSON.stringify(row)}</pre>)}</details></section></div>
}



